#!/usr/bin/env python3
"""Generate, customize, and build every Zephyr federate in an LF source file."""

from __future__ import annotations

import argparse
import ipaddress
import os
import re
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


INTERFACE_RE = re.compile(
    r'@interface_(?:tcp|rudp)\s*\(\s*address\s*=\s*"([^"]+)"[^)]*\)'
    r"(?:\s*@[A-Za-z_]\w*(?:\s*\([^)]*\))?)*"
    r"\s*([A-Za-z_]\w*)\s*=",
    re.DOTALL,
)

CDC_CONSOLE_SOURCE = """\
/* Generated by build.py. Keep the CDC console observable even when LF startup
 * or Ethernet initialization completes before a host opens the serial port.
 */
#include <stdint.h>

#include <pico/bootrom.h>
#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/drivers/uart.h>
#include <zephyr/kernel.h>
#include <zephyr/shell/shell.h>
#include <zephyr/sys/printk.h>

static void lf_cdc_console_notifier(void *unused1, void *unused2, void *unused3)
{
    const struct device *console = DEVICE_DT_GET(DT_CHOSEN(zephyr_console));
    uint32_t dtr = 0;

    ARG_UNUSED(unused1);
    ARG_UNUSED(unused2);
    ARG_UNUSED(unused3);

    while (!device_is_ready(console)) {
        k_sleep(K_MSEC(100));
    }

    while (dtr == 0U) {
        (void)uart_line_ctrl_get(console, UART_LINE_CTRL_DTR, &dtr);
        k_sleep(K_MSEC(100));
    }

    printk("\\r\\nLF W5500 firmware alive; CDC console connected.\\r\\n");
}

K_THREAD_DEFINE(lf_cdc_console_notifier_thread, 1024,
                lf_cdc_console_notifier, NULL, NULL, NULL,
                K_PRIO_PREEMPT(10), 0, 0);

static int cmd_bootsel(const struct shell *shell, size_t argc, char **argv)
{
    ARG_UNUSED(argc);
    ARG_UNUSED(argv);

    shell_print(shell, "Rebooting into RP2040 BOOTSEL mode...");
    k_sleep(K_MSEC(100));
    reset_usb_boot(0, 0);
}

SHELL_CMD_REGISTER(bootsel, NULL,
                   "Reboot into the RP2040 USB mass-storage bootloader.",
                   cmd_bootsel);
"""

CDC_CMAKE_BLOCK = """\

# Added by build.py: CDC sign-of-life and RP2040 BOOTSEL shell support.
target_sources(${LF_MAIN_TARGET} PRIVATE cdc_console.c)
"""


@dataclass(frozen=True)
class Federate:
    name: str
    ipv4: ipaddress.IPv4Address
    mac: tuple[int, int, int, int, int, int]

    @property
    def mac_dts(self) -> str:
        return " ".join(f"{octet:02x}" for octet in self.mac)

    @property
    def mac_text(self) -> str:
        return ":".join(f"{octet:02x}" for octet in self.mac)


def log(message: str) -> None:
    print(message, flush=True)


def run(command: list[str], cwd: Path) -> None:
    log(f"$ {' '.join(shlex.quote(part) for part in command)}")
    subprocess.run(command, cwd=cwd, check=True)


def parse_federates(lf_file: Path) -> list[Federate]:
    source = lf_file.read_text(encoding="utf-8")
    matches = INTERFACE_RE.findall(source)
    if not matches:
        raise ValueError(
            f"no @interface_tcp or @interface_rudp federates with explicit addresses found in {lf_file}"
        )
    if len(matches) > 255:
        raise ValueError("cannot assign unique one-byte MAC suffixes to more than 255 federates")

    federates: list[Federate] = []
    names: set[str] = set()
    addresses: set[ipaddress.IPv4Address] = set()
    for index, (address_text, name) in enumerate(matches, start=1):
        try:
            address = ipaddress.IPv4Address(address_text)
        except ipaddress.AddressValueError as error:
            raise ValueError(f"{name} has an invalid IPv4 address: {address_text}") from error
        if name in names:
            raise ValueError(f"duplicate federate name: {name}")
        if address in addresses:
            raise ValueError(f"duplicate federate IPv4 address: {address}")
        if address.is_loopback or address.is_unspecified or address.is_multicast:
            raise ValueError(f"{name} must use a unicast, non-loopback IPv4 address: {address}")

        # 02 sets the locally administered bit and leaves the multicast bit clear.
        federates.append(Federate(name, address, (0x02, 0x00, 0x00, 0x00, 0x00, index)))
        names.add(name)
        addresses.add(address)

    networks = {ipaddress.IPv4Network(f"{item.ipv4}/24", strict=False) for item in federates}
    if len(networks) != 1:
        raise ValueError("all federate IPv4 addresses must be in the same /24 subnet")
    return federates


def resolve_lf_file(project_root: Path, source: str) -> Path:
    source_root = (project_root / "src").resolve()
    requested = Path(source)
    if requested.suffix == "":
        requested = requested.with_suffix(".lf")
    if requested.suffix != ".lf":
        raise ValueError(f"LF source must have a .lf extension: {source}")

    if requested.is_absolute():
        candidate = requested.resolve()
    elif requested.parts and requested.parts[0] == "src":
        candidate = (project_root / requested).resolve()
    else:
        candidate = (source_root / requested).resolve()
    if candidate.parent != source_root:
        raise ValueError(f"LF source must be a direct child of {source_root}: {source}")
    if not candidate.is_file():
        raise ValueError(f"LF source not found: {candidate}")
    return candidate


def write_if_changed(path: Path, content: str) -> None:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def customize_project(project: Path, common_config: Path, federate: Federate) -> None:
    config = common_config.read_text(encoding="utf-8").rstrip()
    config += (
        "\n\n# Generated by build.py from the federate's LF interface address.\n"
        f'CONFIG_NET_CONFIG_MY_IPV4_ADDR="{federate.ipv4}"\n'
    )
    write_if_changed(project / "prj.conf", config)

    overlay = (
        "/* Generated by build.py; select USB CDC and set the federate MAC. */\n"
        "/ {\n"
        "    chosen {\n"
        "        zephyr,console = &cdc_acm_uart0;\n"
        "        zephyr,shell-uart = &cdc_acm_uart0;\n"
        "    };\n"
        "};\n\n"
        "&zephyr_udc0 {\n"
        "    cdc_acm_uart0: cdc_acm_uart0 {\n"
        '        compatible = "zephyr,cdc-acm-uart";\n'
        "    };\n"
        "};\n\n"
        "&ethernet {\n"
        f"    local-mac-address = [{federate.mac_dts}];\n"
        "};\n"
    )
    write_if_changed(project / "app.overlay", overlay)

    write_if_changed(project / "cdc_console.c", CDC_CONSOLE_SOURCE)
    cmake_file = project / "CMakeLists.txt"
    cmake = cmake_file.read_text(encoding="utf-8")
    if "target_sources(${LF_MAIN_TARGET} PRIVATE cdc_console.c)" not in cmake:
        write_if_changed(cmake_file, cmake.rstrip() + "\n" + CDC_CMAKE_BLOCK)


def find_lfc() -> Path:
    reactor_uc = os.environ.get("REACTOR_UC_PATH")
    if not reactor_uc:
        raise RuntimeError("REACTOR_UC_PATH is not set")
    lfc = Path(reactor_uc).expanduser().resolve() / "lfc" / "bin" / "lfc-dev"
    if not lfc.is_file():
        raise RuntimeError(f"lfc-dev not found: {lfc}")
    return lfc


def find_west(project_root: Path) -> str:
    west = shutil.which("west")
    if west:
        return west

    workspace_west = project_root.parents[1] / "venv" / "bin" / "west"
    if workspace_west.is_file():
        return str(workspace_west)
    raise RuntimeError("west is not on PATH and workspace venv/bin/west was not found")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        default="PingPong.lf",
        metavar="FILE",
        help="LF file in src/ to build; .lf is optional (default: PingPong.lf)",
    )
    parser.add_argument(
        "--skip-generate",
        action="store_true",
        help="reuse the existing src-gen tree and only customize/build it",
    )
    parser.add_argument(
        "--pristine",
        choices=("auto", "always", "never"),
        default="auto",
        help="west pristine policy for each federate (default: auto)",
    )
    parser.add_argument(
        "--board",
        default="w5500_evb_pico",
        help="Zephyr board passed to west (default: w5500_evb_pico)",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(__file__).resolve().parent
    common_config = project_root / "prj.conf"

    try:
        lf_file = resolve_lf_file(project_root, args.source)
        generated_root = project_root / "src-gen" / lf_file.stem
        west = find_west(project_root)
        federates = parse_federates(lf_file)
        if not args.skip_generate:
            lfc = find_lfc()
            run([str(lfc), str(lf_file.relative_to(project_root)), "-n"], project_root)

        for federate in federates:
            generated_project = generated_root / federate.name
            if not (generated_project / "CMakeLists.txt").is_file():
                raise RuntimeError(f"generated project not found: {generated_project}")

            customize_project(generated_project, common_config, federate)
            log(f"\n{federate.name}: IPv4 {federate.ipv4}, MAC {federate.mac_text}")
            run(
                [
                    west,
                    "build",
                    "--pristine",
                    args.pristine,
                    "--board",
                    args.board,
                    "--build-dir",
                    str(generated_project / "build"),
                    str(generated_project),
                    "--",
                    f"-DOVERLAY_CONFIG={generated_project / 'prj.conf'}",
                    f"-DDTC_OVERLAY_FILE={generated_project / 'app.overlay'}",
                ],
                project_root,
            )
    except (OSError, RuntimeError, ValueError, subprocess.CalledProcessError) as error:
        log(f"ERROR: {error}")
        return 1

    log("\nBuilt all federates successfully.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
