# This is the optional user-specific configuration file.

# CONFIG_LOG_RUNTIME_FILTERING=y

# For iot-lab, we need to use UART instead of RTT for logging:
CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n
CONFIG_LOG_BACKEND_RTT=n
CONFIG_UART_CONSOLE=y
CONFIG_LOG_BACKEND_UART=y

# For RUDP:
# CONFIG_NET_TCP=n

CONFIG_IEEE802154_DW3000=y
CONFIG_IEEE802154_NRF5=n

# DW3000 UWB supports HRP UWB channels (use 5 or 9, not 2.4 GHz channel 26).
CONFIG_NET_CONFIG_IEEE802154_CHANNEL=5