# This is the optional user-specific configuration file.

# CONFIG_LOG_BACKEND_RTT=n
# CONFIG_LOG_BACKEND_UART=n
# CONFIG_SHELL_BACKEND_RTT=y
# CONFIG_CONSOLE=y
# CONFIG_LOG=y
# CONFIG_NET_SHELL=y
# CONFIG_SHELL=y
# CONFIG_NET_L2_IEEE802154_SHELL=y
# CONFIG_DEBUG_INFO=n
CONFIG_NET_L2_IEEE802154_RADIO_DFLT_TX_POWER=5