if(CONFIG_SYNCHROFLY)
  add_subdirectory(timesync)
  add_subdirectory(scheduling)
  add_subdirectory(localization)
  add_subdirectory(ranging)
  add_subdirectory(logging)
  add_subdirectory_ifdef(CONFIG_SYNCHROFLY_TRACING_SYSTEMVIEW tracing)
  add_subdirectory(system)
  add_subdirectory(management)
  add_subdirectory(blocks)
  add_subdirectory(communication)
  add_subdirectory_ifdef(CONFIG_SYNCHROFLY_BT bluetooth)
  add_subdirectory_ifdef(CONFIG_NODE_TABLE node_table)
  add_subdirectory(bias_correction)
  add_subdirectory_ifdef(CONFIG_SYNCHROFLY_SWARM_RANGING swarm_ranging)
  add_subdirectory_ifdef(CONFIG_FIRMWARE_STATS stats)

  add_subdirectory_ifdef(CONFIG_CRAZYFLIE crazyflie)
endif()
