# This is the optional user-specific configuration file.

# CONFIG_LOG_BACKEND_RTT=n
# CONFIG_LOG_BACKEND_UART=n
# CONFIG_SHELL_BACKEND_RTT=y
# CONFIG_CONSOLE=y
# CONFIG_LOG=y
# CONFIG_NET_SHELL=y
# CONFIG_SHELL=y
# CONFIG_NET_L2_IEEE802154_SHELL=y
# CONFIG_DEBUG_INFO=n
CONFIG_NET_L2_IEEE802154_RADIO_DFLT_TX_POWER=5

# TODO: Test RUDP with fewer buffers and packets,
# we use UDP! Also, we could try to check if we can
# lower the RUDP channel buffer size to save RAM.
# 1024 bytes is ridiculous, but unfortunately, the biggest
# possible protobuf serializations are ~870ish bytes, so
# in theory, we need a max of round about 1kiB... 
# Might be a nice idea to use, in the rudp network channel,
# a layout of lots of smaller buffers, and then use a 
# scatter-gather approach to fill them up, instead of
# using one big buffer per channel. 
# This means that we might need to move lots of memory,
# but I guess it's reasonable to say that most of the arriving
# packets have a size of only dozens of bytes, so they will not
# occupy more than one buffer fragment. 

# CONFIG_NET_PKT_RX_COUNT=2
# CONFIG_NET_PKT_TX_COUNT=2
# CONFIG_NET_BUF_RX_COUNT=16
# CONFIG_NET_BUF_TX_COUNT=16